add hw2
KlyushkinDimaJob/DimaKlyushkin_LevelUP pull request #4
Opened 2023-05-27 11:09 UTC by KlyushkinDimaJob

2023-05-29 14:51 UTC, khda91 requested changes
Не плохая работа, но нужно исправить комментарии

2023-05-29 14:51 UTC, khda91 commented on pom.xml
> +            <id>positive test</id>
Для имён профилей лучше не использовать в качестве разделителя пробельный символ. Лучше всего подходит `_` или `-`

2023-05-29 14:51 UTC, khda91 commented on pom.xml
> +            <id>negative test</id>
Для имён профилей лучше не использовать в качестве разделителя пробельный символ. Лучше всего подходит `_` или `-`

2023-05-29 14:51 UTC, khda91 commented on pom.xml
> +            <id>all test</id>
Для имён профилей лучше не использовать в качестве разделителя пробельный символ. Лучше всего подходит `_` или `-`

2023-05-29 14:51 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +        return false;
В задании сказано, что `Счастливым билетом считается билет, номер которого состоит из 6 цифр`
Вопрос: Если пользователь ввёл не правильно данные, что должно произойти?

2023-05-29 16:15 UTC, KlyushkinDimaJob commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +        return false;
Ожидается исключение?

2023-05-29 16:37 UTC, KlyushkinDimaJob commented on pom.xml
> +            <id>positive test</id>
Поправил

2023-05-29 16:38 UTC, KlyushkinDimaJob commented on pom.xml
> +            <id>negative test</id>
Поправил

2023-05-29 16:38 UTC, KlyushkinDimaJob commented on pom.xml
> +            <id>all test</id>
Поправил

2023-05-29 19:12 UTC, khda91 commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +        return false;
Именно) Считай как пароль не правильный ввёл)

2023-05-30 08:06 UTC, KlyushkinDimaJob commented on src/main/java/ru/levelp/at/homework2/LuckyTicket.java
> +        return false;
Поправил

2023-06-05 10:01 UTC, khda91 approved these changes
Домашняя работа принята

2023-06-08 15:33 UTC, merged