add hw3
KlyushkinDimaJob/DimaKlyushkin_LevelUP pull request #5
Opened 2023-06-08 15:34 UTC by KlyushkinDimaJob

2023-06-11 17:49 UTC, khda91 requested changes
Замечания написал только в 1 классе, но он применительны ко всем

2023-06-11 17:49 UTC, khda91 commented on src/main/java/ru/levelp/at/utils/SleepUtils.java
> +public final class SleepUtils {
Зачем данный. класс тут нужен?

2023-06-11 17:49 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        sleep(1000);
В тестах не должно быть вызовов метода, в которых фигурирует `Thread.sleep`. Любые действия связанные с ожиданиями элементов должны происходить через встроенные механизмы в Selenium

2023-06-11 17:49 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        assertTrue(driver.getTitle().contains("Входящие - Почта Mail.ru"), "Вход в почту не выполнен");
А почему не использовать тут `assertEquals` или подключить `assertJ`?

2023-06-11 17:49 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        driver.navigate().to("https://e.mail.ru/tomyself/");
Прямой переход по ссылке?

2023-06-11 17:49 UTC, khda91 commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +    @BeforeMethod
Может быть имеет смысл их вынести в общий класс от которого можно наследоваться будет?

2023-06-11 18:08 UTC, KlyushkinDimaJob commented on src/main/java/ru/levelp/at/utils/SleepUtils.java
> +public final class SleepUtils {
А разве не в том и смысл второй дз по selenium, чтобы добавить явные и неявные ожидания? А в первой все ожидания через Thread.sleep сделать

2023-06-11 20:44 UTC, KlyushkinDimaJob commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        assertTrue(driver.getTitle().contains("Входящие - Почта Mail.ru"), "Вход в почту не выполнен");
assertEquals - зачем, если просто добавится второй параметр, в который передам true?
assertJ - что поменяется если я его использую?

2023-06-11 20:46 UTC, KlyushkinDimaJob commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        driver.navigate().to("https://e.mail.ru/tomyself/");
В этом есть что-то плохое? Кажется, что это более надежный метод, чем клик по кнопке

2023-06-11 20:48 UTC, KlyushkinDimaJob commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +    @BeforeMethod
Да, думаю так и стоит сделать. Поправлю

2023-06-18 19:09 UTC, KlyushkinDimaJob commented on src/main/java/ru/levelp/at/utils/SleepUtils.java
> +public final class SleepUtils {
Удалил данный класс

2023-06-18 19:10 UTC, KlyushkinDimaJob commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        sleep(1000);
Заменил на явные и неявные ожидания

2023-06-18 19:12 UTC, KlyushkinDimaJob commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        assertTrue(driver.getTitle().contains("Входящие - Почта Mail.ru"), "Вход в почту не выполнен");
Из-за отказа от перехода по ссылкам изменилась логика и данный код был удален

2023-06-18 19:12 UTC, KlyushkinDimaJob commented on src/test/java/ru/levelp/at/homework3/DeleteMessageTest.java
> +        driver.navigate().to("https://e.mail.ru/tomyself/");
Все переходы по ссылкам были заменены на клик по соответствующим кнопкам

2023-06-19 20:48 UTC, khda91 approved these changes
Работа принята

2023-06-24 16:27 UTC, merged